-- Deploy ofrigo:2.insert to pg

BEGIN;

INSERT INTO account(last_name, first_name, email, password, role) VALUES
('lienard', 'kevin', 'kevin@gmail.com', '1234', 'admin');

INSERT INTO message(title, content, account_id) VALUES
('test', 'Ceci est un test', 1);

--INSERT INTO category(label) VALUES

INSERT INTO ingredient(label) VALUES
('Farine'),
('Sucre '),
('Semoule'),
('Sucre vanillé'),
('Beurre'),
('Crème fraîche'),
('Eau'),
('Sel'),
('Oeuf'),
('Sucre fin'),
('Levure chimique'),
('Lait'),
('Pomme'),
('Persil'),
('Poivre'),
('Moules'),
('Echalote'),
('Vin blanc sec'),
('Crème fraîche épaisse'),
('Roquefort'),
('Beurre demi-sel'),
('Levure'),
('Huile d''olive'),
('Sucre en poudre'),
('Yaourt nature'),
('Nutella'),
('Courgette'),
('Gruyère râpé'),
('Crème épaisse'),
('Ail'),
('Chèvre'),
('Muscade'),
('Biscuits à la cuillère'),
('Mascarpone'),
('Café'),
('Cacao'),
('Marsala'),
('Chocolat'),
('Huile'),
('Chorizo'),
('Vanille'),
('Pâte à tartiner'),
('Sauce tomate'),
('Spaghetti'),
('Saumon fumé'),
('Citron'),
('Ciboulette'),
('Sucre semoule'),
('Beurre doux'),
('Blanc d''oeuf'),
('Aneth'),
('Menthe'),
('Jaune d''oeuf'),
('Pâte feuilletée'),
('Oignon jaune'),
('Filet mignon'),
('Jambon blanc'),
('Miel'),
('Anis'),
('Gingembre'),
('Quatre-épices'),
('Cannelle'),
('Pâte brisée'),
('Oignon'),
('Sauté de veau'),
('Pulpe de tomate'),
('Olives vertes'),
('Basilic'),
('Bouquet garni'),
('Dés de jambon'),
('Purée'),
('Tomate'),
('Viande hachée'),
('Herbes de Provence'),
('Parmesan');

INSERT INTO recipe(name, picture, rate, difficulty, time) VALUES
('Gaufres à la crème fraîche', './app/picture/Gaufres-à-la-crème-fraîche.jpg', 4.7, 'Moyen', 40),
('Beignets de pomme de mon papi', './app/picture/Beignets-de-pomme-de-mon-papi.jpg', 4.8, 'Difficile', 35),
('Pancake de Nawal', './app/picture/Pancake-de-Nawal.jpg', 4.9, 'Moyen', 35),
('Moules au roquefort', './app/picture/Moules-au-roquefort.jpg', 4.9, 'Moyen', 35),
('Pâte à pizza épaisse et moelleuse', './app/picture/Pâte-à-pizza-épaisse-et-moelleuse.jpg', 4.6, 'Difficile', 20),
('Muffins coeur de Nutella', './app/picture/Muffins-coeur-de-Nutella.jpg', 4.6, 'Moyen', 30),
('Gratin de courgettes au chèvre', './app/picture/Gratin-de-courgettes-au-chèvre.jpg', 4.7, 'Moyen', 40),
('Tiramisu au café', './app/picture/Tiramisu-au-café.jpg', 4.9, 'Difficile', 15),
('Mousse au chocolat de maman', './app/picture/Mousse-au-chocolat-de-maman.jpg', 4.7, 'Difficile', 23),
('Gâteau aux pommes croustillant de maman', './app/picture/Gâteau-aux-pommes-croustillant-de-maman.jpg', 4.7, 'Moyen', 40),
('Madeleines salées courgette chorizo', './app/picture/Madeleines-salées-courgette-chorizo.jpg', 4.8, 'Difficile', 20),
('Muffins à la pâte à tartiner et aux pépites de chocolat', './app/picture/Muffins-à-la-pâte-à-tartiner-et-aux-pépites-de-chocolat.jpg', 4.6, 'Moyen', 35),
('Pâtes au saumon fumé à la vince', './app/picture/Pâtes-au-saumon-fumé-à-la-vince.jpg', 4.7, 'Moyen', 25),
('Pancake Moelleux : recette facile', './app/picture/Pancake-Moelleux.jpg', 4.8, 'Difficile', 14),
('Meringue : recette facile', './app/picture/Meringue.jpg', 4.8, 'Difficile', 5),
('Les Timbales de Jeanne (saumon à la mousse de courgettes au micro-ondes)', './app/picture/Les-Timbales-de-Jeanne.jpg', 4.8, 'Difficile', 18),
('Béchamel rapide et facile', './app/picture/Béchamel-rapide-et-facile.jpg', 4.8, 'Difficile', 7),
('Crème pâtissière', './app/picture/Crème-pâtissière.jpg', 4.9, 'Facile', 20),
('Filet mignon en croûte', './app/picture/Filet-mignon-en-croûte.jpg', 4.8, 'Facile', 60),
('Crumble simple', './app/picture/Crumble-simple.jpg', 4.9, 'Facile', 35),
('Pain d''épices', './app/picture/Pain-d''épices.jpg', 4.8, 'Moyen', 90),
('Tarte aux pommes à l''Alsacienne', './app/picture/Tarte-aux-pommes-à-l''Alsacienne.jpg', 4.8, 'Facile', 55),
('Pancakes faciles et rapides', './app/picture/Pancakes-faciles-et-rapides.jpg', 4.8, 'Difficile', 15),
('Sauté de veau au chorizo', './app/picture/Sauté-de-veau-au-chorizo.jpg', 4.8, 'Facile', 80),
('Cake salé au jambon et aux olives', './app/picture/Cake-salé-au-jambon-et-aux-olives.jpg', 4.8, 'Moyen', 65),
('Hachis Parmentier', './app/picture/Hachis-Parmentier.jpg', 4.8, 'Moyen', 45);

INSERT INTO quantity(content, recipe_id) VALUES
('500 g de farine', 1),
('50 g de sucre semoule', 1),
('2 sachets de sucre vanillé', 1),
('150 g de beurre fondu', 1),
('25 cl de crème fraîche', 1),
('50 cl d''eau', 1),
('1 pincée de sel', 1),
('4 oeufs', 1),
('300 g de farine', 2),
('3 c.à.s de sucre fin', 2),
('1 paquet de sucre vanillé', 2),
('1 c.à.c de levure chimique', 2),
('2 oeufs', 2),
('25 cl de lait', 2),
('3 pommes (évidées et coupées en rondelles pas trop épaisses)', 2),
('300 g de farine', 3),
('2 sachets de sucre vanillé (ou 1 sachet de sucre à la fleur d''oranger et 1 à la vanille)', 3),
('1 c.à.s de sucre', 3),
('100 g de beurre fondu tiède', 3),
('1 pincée de sel', 3),
('1 sachet de levure chimique', 3),
('4 oeufs', 3),
('40 cl de lait', 3),
('persil', 4),
('poivre', 4),
('sel', 4),
('1.5 kg de moules', 4),
('3 échalotes', 4),
('25 cl de vin blanc sec', 4),
('50 cl de crème fraîche épaisse', 4),
('125 g de roquefort', 4),
('beurre demi-sel', 4),
('350 g de farine (type pâte à pain) + 100 g pour travailler la pâte', 5),
('c.à.c de sel', 5),
('1 sachet de levure boulangère', 5),
('3 c.à.s d''huile d''olive', 5),
('25 cl d''eau tiède', 5),
('280 g de farine', 6),
('1/2 sachet de levure chimique', 6),
('1 pincée de sel', 6),
('100 g de sucre en poudre', 6),
('1 sachet de sucre vanillé', 6),
('100 g de beurre fondu', 6),
('beurre et farine pour le moule', 6),
('2 oeufs', 6),
('10 cl de lait', 6),
('1 yaourt nature', 6),
('1 petit pot de nutella (ou autre pâte à tartiner au chocolat)', 6),
('1 courgette ou 2 moyennes', 7),
('gruyère râpé', 7),
('poivre', 7),
('sel', 7),
('huile d''olive', 7),
('10 cl de crème épaisse', 7),
('2 gousses d''ail', 7),
('1 oeuf', 7),
('1/2 bûchette de chèvre', 7),
('muscade', 7),
('100 g de sucre', 8),
('48 biscuits à la cuillère', 8),
('1 pincée de sel', 8),
('500 g de mascarpone', 8),
('4 oeufs', 8),
('35 cl de café fort froid', 8),
('2 c.à.s de cacao non sucré', 8),
('1 c.à.s de marsala à l''amande ou autre alcool', 8),
('1 tablette de chocolat', 9),
('50 g de beurre', 9),
('3 c.à.s de sucre', 9),
('1 petit pot de crème fraîche (10cl)', 9),
('6 oeufs', 9),
('80 g de beurre', 10),
('100 g de sucre', 10),
('1 sachet de sucre vanillé', 10),
('1 oeuf', 10),
('100 g de farine', 10),
('90 g de sucre', 10),
('3 cl d''huile', 10),
('1 pincée de sel', 10),
('1/2 paquet de levure', 10),
('5 cl de lait', 10),
('3 pommes', 10),
('240 g de farine', 11),
('1.5 sachet de levure chimique (17 g)', 11),
('45 g de gruyère râpé', 11),
('9 c.à.s d''huile de  tournesol ou colza', 11),
('350 g de courgette', 11),
('6 oeufs', 11),
('180 g de chorizo (doux ou fort selon les goûts)', 11),
('180 g de farine à levure incorporée', 12),
('90 g de sucre', 12),
('125 g de beurre fondu', 12),
('1/2 c.à.c de sel', 12),
('1/2 c.à.c de vanille liquide', 12),
('60 g de chocolat', 12),
('1 oeuf', 12),
('10 cl de lait', 12),
('6 c.à.c de pâte à tartiner', 12),
('1 noix de beurre', 13),
('1 c.à.c de sauce tomate (pour la couleur)', 13),
('poivre (selon le goût...)', 13),
('500 g de spaghetti ou tagliatelles', 13),
('200 g de saumon fumé en barquette', 13),
('1 gros pot de crème fraîche épaisse (50 cl)', 13),
('1 échalote', 13),
('1 de citron', 13),
('10 cl de vin blanc sec', 13),
('2 c.à.s de ciboulette ciselée', 13),
('250 g de farine', 14),
('30 g de sucre semoule', 14),
('1 sachet de levure traditionnelle', 14),
('65 g de beurre doux', 14),
('1 pincée de sel', 14),
('2 oeufs', 14),
('30 cl de lait', 14),
('250 g de sucre semoule', 15),
('4 blancs d''oeuf', 15),
('2 courgettes', 16),
('1 c.à.s d''huile d''olive', 16),
('aneth', 16),
('sel', 16),
('poivre', 16),
('4 tranches de saumon fumé', 16),
('3 oeufs', 16),
('10 cl de crème fraîche épaisse', 16),
('1 petite gousse d''ail', 16),
('menthe', 16),
('20 g de beurre', 17),
('2 c.à.s de farine', 17),
('sel', 17),
('poivre', 17),
('25 cl de lait', 17),
('100 g de farine', 18),
('200 g de sucre', 18),
('1 gousse de vanille', 18),
('1 l de lait', 18),
('4 jaunes d''oeuf', 18),
('2 pâtes feuilletées', 19),
('200 g de gruyère râpé', 19),
('2 oignons jaunes', 19),
('2 filets mignons de porc', 19),
('4 tranches de jambon blanc', 19),
('2 jaunes d''oeuf', 19),
('150 g de farine', 20),
('75 g de beurre', 20),
('120 g de sucre', 20),
('3 pommes (ou 3 poires)', 20),
('250 g de miel', 21),
('250 g de farine', 21),
('100 g de sucre en poudre', 21),
('1 sachet de levure chimique', 21),
('1 sachet de sucre vanillé', 21),
('1 c.à.c d''anis vert', 21),
('1 c.à.c de gingembre en poudre', 21),
('1 c.à.c de quatre-épices', 21),
('1 c.à.c de muscade râpée', 21),
('1 c.à.c de cannelle en poudre', 21),
('2 oeufs', 21),
('10 cl de lait', 21),
('1 pâte brisée', 22),
('25 cl de crème fraîche', 22),
('100 g de sucre en poudre', 22),
('1 sachet de sucre vanillé', 22),
('3 pommes (selon la grosseur)', 22),
('2 oeufs', 22),
('1 c.à.s de sucre blanc', 23),
('1 c.à.s d''huile ou de beurre fondu', 23),
('150 g de farine', 23),
('1 bonne cuillère à café de levure', 23),
('1 oeuf', 23),
('200 ml de lait', 23),
('4 oignons', 24),
('2 c.à.s d''huile', 24),
('1 kg de sauté de veau', 24),
('2 boîtes de pulpe de tomate', 24),
('1 chorizo (doux ou extra fort selon votre goût)', 24),
('1 pot d''olives vertes dénoyautées', 24),
('1 bouquet de basilic', 24),
('1 bouquet garni', 24),
('1 gousse d''ail', 24),
('150 g de farine', 25),
('75 g de gruyère râpé', 25),
('1 sachet de levure chimique', 25),
('1 c.à.s d''huile', 25),
('100 g de dés de jambon', 25),
('150 g d''olives vertes dénoyautées', 25),
('4 oeufs', 25),
('10 cl de lait', 25),
('300 g de purée', 26),
('2 oignons', 26),
('2 tomates fraîches ou pelées', 26),
('1 c.à.s de farine', 26),
('30 g de beurre', 26),
('50 g de fromage râpé', 26),
('sel', 26),
('poivre', 26),
('400 g de viande hachée', 26),
('2 gousses d''ail', 26),
('1 pincée de herbes de Provence', 26),
('1 jaune d''oeuf', 26),
('30 g de Parmesan', 26);

INSERT INTO step(content, recipe_id) VALUES
('Séparer les blancs d''oeuf des jaunes, mettre les blancs dans un récipient à part.', 1),
('Dans un deuxième récipient, mélanger tous les autres ingrédients en une pâte bien lisse.', 1),
('Monter les blancs d''oeuf en neige bien ferme, les ajouter délicatement à la pâte en soulevant la masse (former des 8 avec une cuillère en bois).', 1),
('Verser une louche de pâte dans l''appareil chauffé et laisser cuire ainsi de suite jusqu''à épuisement du stock !', 1),
('Déguster les gaufres bien chaudes !', 1),
('Mélanger les ingrédients pour la pâte dans l''ordre indiqué.', 2),
('Tremper chaque rondelle de pomme dans cette pâte et mettre à frire.', 2),
('Dégustez, c''est prèt.', 2),
('Séparer les jaunes d''oeuf des blancs.', 3),
('Mélanger les jaunes, les sucres, le lait, la farine, la levure et le sel sans faire de gumeaux.', 3),
('Ajouter le beurre fondu puis incorporer délicatement les blancs en neige.', 3),
('Chauffer une poêle à blini et déposer une petite louche de pâte.', 3),
('Quand il devient doré en dessous, retourner le pancake et le laisser cuire un instant.', 3),
('Les servir nappés de miel ou de sirop d''érable.', 3),
('Nettoyer les moules (certainement l''opération la plus longue de la recette). Faire fondre une bonne noix de beurre dans une casserole et y faire suer les échalotes finement hachées.', 4),
('Ajouter la crème et le roquefort bien écrasé. Remuer jusqu''à obtenir une pâte bien lisse.', 4),
('Ajouter du persil et assaisonner, maintenir à feu moyen.', 4),
('Pendant ce temps, faire chauffer le vin blanc dans une cocotte et incorporer les moules. Laisser les moules s''ouvrir à couvert pendant environ 5 minutes.', 4),
('Quand elles sont ouvertes, 2 possibilités: soit vous égouttez les moules et vous les arrosez avec la sauce, ce qui est plus onctueux, soit vous conservez le jus de cuisson et vous ajouter la sauce, c''est également très bon mais la sauce est plus liquide. Laisser mijoter 5 minutes.', 4),
('Déguster sans tarder.', 4),
('Mettre 350 g de farine dans un grand saladier puis ajouter successivement le sel, la levure boulangère et l''huile d''olive.', 5),
('Verser petit à petit l''eau tiède tout en mélangeant avec une cuillère en bois.', 5),
('Remuer longuement jusqu''à obtention d''une pâte qui se détache du saladier.', 5),
('Laisser reposer la pâte pendant 1h en couvrant le saladier avec un torchon dans un endroit chaud.', 5),
('Après le temps de repos, déposer de la farine sur votre plan de travail y déposer la pâte à pizza.', 5),
('La travailler comme on travaillerait une pâte à pain.', 5),
('Façonner votre pizza aux dimensions de votre plaque à four où l''idéal, c''est de déposer la pâte sur du papier cuisson.', 5),
('Agrémenter votre pizza au grès de vos envies ou de vos restes dans le frigo.', 5),
('Préchauffer votre four à 180°C.', 6),
('Dans un saladier, mélanger la farine, la levure chimique et le sel.', 6),
('Dans un autre saladier, battre les oeufs avec un fouet puis, ajouter le sucre en poudre et le sachet de sucre vanillé.', 6),
('Bien mélanger.', 6),
('Verser le beurre fondu sur ce mélange sans cesser de remuer puis ajouter le lait et le yaourt.', 6),
('Y incorporer le premier mélange farine-levure-sel.', 6),
('Beurrer et fariner le moule à muffins.', 6),
('Le remplir au 1/3 avec la préparation, former une petite cuvette, y déposer une noix de nutella bien au centre puis, recouvrir en répartissant le reste de la pâte.', 6),
('Mettre à cuire les muffins au four pendant 20 minutes environ.', 6),
('Les sortir et attendre 5 minutes avant de les démouler. Se déguste légèrement tièdes.', 6),
('Laver les courgettes, les couper en rondelles pas trop épaisses et faire revenir dans l''huile d''olive jusqu''à ce qu''elles soient tendres, une dizaine de minutes, en remuant.', 7),
('Dans un bol, battre : la crème et l''oeuf.', 7),
('Ajouter le sel, le poivre, muscade et les gousses d''ail finement émincées.', 7),
('Une fois tendres, égoutter un peu les courgettes du surplus d''huile et les mettre dans un petit plat à gratin.', 7),
('Verser dessus la préparation à la crème.', 7),
('Disposer sur le plat des rondelles de chèvres et un peu de gryuère râpée.', 7),
('Enfourner entre 180 et 200°C pour 30 mn, le flan doit avoir pris.', 7),
('Séparer le blanc des jaunes des œufs. Dans un saladier mélanger les jaunes d''oeuf avec le sucre au fouet puis rajouter le Marsala et le mascarpone.', 8),
('Dans un autre saladier, battre les blancs d''oeuf en neige au fouet avec la pincée de sel.', 8),
('Ajouter les oeufs en neige à la première préparation en mélangeant délicatement afin d''obtenir un appareil mousseux et léger.', 8),
('Tremper les biscuits dans le café froid et en tapisser le fond de votre plat puis étaler par dessus votre préparation - renouveler l''opération encore une fois.', 8),
('Saupoudrer le tiramisu de cacao pour finir.', 8),
('Mettre au frais au moins 12 h.', 8),
('Faire fondre le beurre dans une casserole.', 9),
('Garder 40 g de chocolat et casser le reste en morceaux.', 9),
('Ajouter le chocolat au beurre, faire cuire à feu doux et bien remuer puis obtenir un mélange lisse.', 9),
('Laisser refroidir le mélange.', 9),
('Pendant ce temps, casser les œufs en séparant les jaunes des blancs.', 9),
('Mélanger les jaunes au sucre puis ajouter le mélange (chocolat-beurre) et la crème fraîche.', 9),
('Monter les blancs en neige et les incorporer dans le mélange.', 9),
('Veillez à bien soulever votre cuillère en bois pour aérer au maximum le mélange, la mousse en sera plus légère.', 9),
('Mettez le mélange dans des ramequins individuels.', 9),
('Pour la décoration, râpez le reste de chocolat noir en morceau. Faites de même avec le chocolat blanc. Saupoudrez la mousse avec ces copeaux de chocolat ainsi que des morceaux de noisette.', 9),
('Bonne dégustation !', 9),
('Mélanger la farine, le sucre la levure et le sel. Ajouter l''huile, le lait et l''oeuf. Bien mélanger.', 10),
('Verser dans un moule à manqué beurré ET fariné.', 10),
('Y déposer les tranches de pommes (épluchées et coupées en 12 tranches à peu près!) tout en les chevauchant.', 10),
('Mettre au four 25 minutes à thermostat 6 (180°C).', 10),
('Préparer la crème : faire fondre le beurre et ajouter le sucre, la vanille et l''oeuf.', 10),
('Quand le gâteau commence à dorer et à lever (après 25 mn), verser la crème dessus.', 10),
('Terminer la cuisson (15 minutes).', 10),
('Préchauffer le four à 210°C (thermostat 7).', 11),
('Râper les courgettes, couper le chorizo en petits dés.', 11),
('Dans le bol d''un robot mettre la farine, la levure, les oeufs, l''huile et mettre en route. Une fois que le mélange est homogène ajouter le gruyère puis les courgettes râpées et le chorizo.', 11),
('Mettre dans des alvéoles en silicone ou dans des alvéoles beurrées et enfourner pendant 10 minutes.', 11),
('Préchauffez le four thermostat 7-8 (220°C).', 12),
('Cassez l''oeuf dans un saladier, battez à la fourchette avec le beurre tiédi, le lait et le sel.', 12),
('Incorporez la farine et le sucre ainsi que la vanille liquide sans trop travailler la pate.', 12),
('Ajoutez les pépites de chocolat et mélanger.', 12),
('Disposez dans 6 moules à muffins 1 cuillérée à soupe de pâte puis une grosse cuillère à café de nutella et recouvrez pour terminer par une autre grosse cuillérée à soupe de pâte.', 12),
('Enfournez, à thermostat 7-8 pendant 5 min puis baisser le thermostat à 6 (180°C) et laisser cuire pendant encore 15 min.', 12),
('A la sortie du four, laisser refroidir puis démouler.', 12),
('Ces muffins se dégustent à température ambiante.', 12),
('Faire fondre le beurre dans une casserole et y faire revenir l''échalote hachée jusqu''à ce qu''elle blondisse.', 13),
('Déglacer avec le vin blanc et attendre la reprise de l''ébullition.', 13),
('Ajouter le jus de citron, la crème fraîche, la sauce tomate et la ciboulette.', 13),
('Enfin, ajouter à la préparation le saumon coupé grossièrement en carrés.', 13),
('Laisser chauffer la sauce sur feu très doux pendant la cuisson des pâtes.', 13),
('Servez la sauce et les pâtes séparément.', 13),
('Bon appétit !!!', 13),
('Faire fondre le beurre, dans une casserole à feu doux ou dans un bol au micro-ondes. ', 14),
('Mettre la farine, la levure et le sucre dans un saladier. Mélanger et creuser un puits.', 14),
('Ajouter ensuite les oeufs entiers et fouetter l''ensemble.', 14),
('Laisser reposer la pâte au minimum 1 heure au réfrigérateur.', 14),
('Dans une poêle chaude et légèrement huilée, faire cuire comme des crêpes, mais en les faisant plus petites. Réserver au chaud et déguster.', 14),
('Quelques trucs pour bien réussir ces meringues : sortir les oeufs du réfrigérateur un quart d''heure avant de les utiliser.', 15),
('Ne surtout pas mélanger de jaunes aux blancs d''oeuf.', 15),
('Ajouter une pincée de sel avant de battre les blancs en neige.', 15),
('Utiliser un récipient plus haut que large et utiliser un batteur électrique (bien plus rapide et moins fatiguant)! On peut commencer :', 15),
('Battre les blancs d''oeuf en neige ferme.', 15),
('Ajouter le sucre par petites quantités tout en continuant de battre.', 15),
('Préchauffer le four à 120°C (thermostat 4).', 15),
('Déposer immédiatement de petits tas de meringue sur une plaque de four préalablement recouverte de papier sulfurisé.', 15),
('Cuire entre 30 minutes et 1 heure à 120°C.', 15),
('Au bout de 30 minutes, on obtient des meringues blanches et moelleuses.', 15),
('Au bout d''1 heure, on obtient des meringues rosées, craquantes et fondantes avec un coeur moelleux.', 15),
('Une fois cuites, décoller les meringues délicatement dès la sortie du four et laisser refroidir sur une grille.', 15),
('Rincer, essorer et ciseler l''aneth et la menthe. Peler et émincer la gousse d''ail.', 16),
('Râper les courgettes.', 16),
('Les faire revenir dans 1 cuillère à soupe d''huile d''olive avec l''ail émincé et les herbes ciselées.', 16),
('Assaisonner (mais pas trop, attention au saumon fumé). Réserver et laisser un peu refroidir.', 16),
('Battre les oeufs et la crème en omelette.', 16),
('Mélanger cette préparation avec les courgettes râpées et éventuellement, donner un petit coup de mixeur pour obtenir l''aspect "mousse".', 16),
('Tapisser 4 ramequins avec les tranches de saumon fumé.', 16),
('Verser le mélange omelette-courgettes dans les ramequins tapissés de saumon.', 16),
('Faire cuire au micro-ondes pendant 2 à 3 minutes, selon la puissance (vérifier la cuisson vous-même, il n''y a que ça de vrai !).', 16),
('Déguster !', 16),
('Dans un grand récipient, faire fondre le beurre 1 minute au micro-ondes.', 17),
('Le sortir et ajouter la farine en remuant bien.', 17),
('Porter le lait à ébullition, le laisser bouillir quelques instants.', 17),
('Verser le lait sur le mélange farine/beurre en fouettant. Assaisonner.', 17),
('Remettre le tout au micro-ondes pendant 1 minute.', 17),
('Bien fouetter, c''est prêt !', 17),
('Mélanger les jaunes d''oeuf avec le sucre. Battre au fouet jusqu''à que le mélange blanchisse.', 18),
('Ajouter la farine et bien mélanger avec le mélange sucre/oeufs. Ajouter 1/2 verre de lait pour que le mélange soit plus liquide.', 18),
('Mettre à chauffer le lait. Lorsque le lait est tiède (au bout de 3-4 min) ajouter le mélange oeufs/farine/sucre/lait et la gousse de vanille fendue et grattée avec ses graines.', 18),
('Mélanger au fouet jusqu''à ébullition.', 18),
('A ce moment là, votre crème sera déjà bien épaisse et vous pouvez arrêter la cuisson.', 18),
('Peler et émincer les oignons.', 19),
('Les faire revenir dans une sauteuse avec 20 g de beurre pendant 3 minutes environ.', 19),
('Dans la même sauteuse, faire revenir les filets mignons de chaque côté.', 19),
('Laisser cuire 10 minutes à feu doux.', 19),
('Réincorporer les oignons. Poursuivre la cuisson pendant 5 minutes. Saler, poivrer. Réserver.', 19),
('Dérouler les pâtes feuilletées.', 19),
('Déposer sur chaque pâte deux tranches de jambon et 100 g de gruyère. Saler et poivrer.', 19),
('Y déposer un filet sur chaque pâte garnie et napper de sauce aux oignons.', 19),
('Replier la pâte autour de la viande et souder les bords à l''aide du jaune d''oeuf préalablement battu et d''un pinceau alimentaire.', 19),
('Enfourner pour 45 minutes de cuisson à 200°C (thermostat 6-7).', 19),
('Préchauffer le four à 180°C (thermostat 6). Peler les pommes.', 20),
('Couper les pommes en dés.', 20),
('Dans un saladier, mélanger la farine au sucre,', 20),
('puis au beurre', 20),
('Malaxer le tout avec les doigts pour obtenir une pâte sableuse.', 20),
('Beurrer le moule, y disposer les pommes tranchées (ou les poires) et placer la pâte par dessus.', 20),
('Laisser cuire 25 min. Servir avec une crème anglaise.', 20),
('Faites chauffer 250 g de miel à la casserole ou au micro-ondes.', 21),
('Mélangez la farine avec la levure chimique, les deux sucres et les épices.', 21),
('Ajoutez le miel chaud (en remuant idéalement avec une cuillère en bois).', 21),
('Incorporez petit à petit 2 oeufs, puis un peu de lait juste tiède pour amalgamer le tout.', 21),
('Préchauffez le four à 160°C (thermostat 5-6).', 21),
('Versez la préparation dans un moule à cake bien beurré (utilisez une feuille de papier essuie-tout) et fariné.', 21),
('Enfournez et laissez cuire pendant 1h à 1h15.', 21),
('Démoulez le pain d''épices lorsqu''il a totalement refroidi. Attendez 24 heures au minimum avant de le déguster.', 21),
('Il se garde une semaine, enveloppé dans du papier d''aluminium.', 21),
('Pelez et coupez les pommes en fines tranches.', 22),
('Dans un saladier, mélangez le sucre, les oeufs, le sucre vanillé', 22),
('la crème fraîche', 22),
('Etalez la pâte dans un moule à tarte et piquez le fond à l''aide d''une fourchette. Disposez les pommes sur la pâte et versez le tout sur les pommes (ou versez uniquement la crème)', 22),
('Puis disposer les lamelles de pommes roulées sur elles-même en roses.', 22),
('Enfournez environ 30 minutes, jusqu''à ce que la tarte prenne une belle couleur dorée.', 22),
('Déguster', 22),
('Battre grossièrement l''oeuf et le sucre dans un saladier.', 23),
('Y rajouter le beurre fondu ou l''huile.', 23),
('Mélanger à part la farine et la levure, puis en mélanger la moitié avec la préparation.', 23),
('Délayer progressivement avec le lait tout en rajoutant l''autre moitié de farine petit à petit (cela évitera de créer des grumeaux).', 23),
('Aucun temps de repos n''est nécessaire, si ce n''est juste le temps de faire chauffer votre poêle à feu moyen. Huilez ou beurrez la poêle à l''aide de papier essuie-tout.', 23),
('A l''aide d''une petite louche ou d''une grosse cuillère à sauce, déposer des "ronds" dans la poêle.', 23),
('Lorsque les bulles apparaissent et éclatent, retourner les pancakes et ne pas les laisser plus d''une min sur l''autre face.', 23),
('Emincer l''oignon et détailler le chorizo pelé en rondelles.', 24),
('Découper le veau en morceaux.', 24),
('Faire revenir veau et oignons émincés jusqu''à coloration dans l''huile.', 24),
('Ajouter le chorizo puis la pulpe de tomate, le basilic haché et enfin les olives.', 24),
('Couvrir et faire mijoter à feu doux 1 heure minimum.', 24),
('Ce plat est encore meilleur préparé la veille et réchauffé le jour même.', 24),
('Préchauffer le four à 180°C (thermostat 6).', 25),
('Couper les olives en rondelles.', 25),
('Verser les oeufs dans la farine et mélanger.', 25),
('Ajouter le lait et l''huile puis mélanger.', 25),
('Ajouter le jambon, les olives et le gruyère puis mélanger.', 25),
('Ajouter la levure et, pour ne pas changer, mélanger.', 25),
('Mettre le tout dans un plat à cake au préalable beurré et placer au four 45 min.', 25),
('Hacher l''oignon et l''ail.', 26),
('Les faire revenir dans le beurre jusqu''à ce qu''ils soient tendres.', 26),
('Ajouter les tomates coupées en dés, la viande hachée, la farine, du sel, du poivre et les herbes de Provence.', 26),
('Quand tout est cuit, couper le feu et ajouter le jaune d''oeuf et un peu de parmesan. Bien mélanger.', 26),
('Préchauffer le four à 200°C (thermostat 6-7).', 26),
('Etaler au fond du plat à gratin. Préparer la purée. L''étaler au dessus de la viande. Saupoudrer de fromage râpé et faire gratiner.', 26);

INSERT INTO tag(label) VALUES
('Gaufres à la crème fraîche'),
('Farine'),
('Sucre semoule'),
('Sucre vanillé'),
('Beurre'),
('Crème fraîche'),
('Eau'),
('Sel'),
('Oeuf'),
('Gaufre'),
('Facile'),
('Bon marché'),
('Beignets de pomme de mon papi'),
('Sucre fin'),
('Levure chimique'),
('Lait'),
('Pomme'),
('Beignets sucrés'),
('Rapide'),
('Pancake de Nawal'),
('Sucre'),
('Pancake'),
('Moules au roquefort'),
('Persil'),
('Poivre'),
('Moules'),
('Echalote'),
('Vin blanc sec'),
('Crème fraîche épaisse'),
('Roquefort'),
('Beurre demi-sel'),
('Pâte à pizza épaisse et moelleuse'),
('Levure'),
('Huile d''olive'),
('Pizza'),
('Muffins coeur de Nutella'),
('Sucre en poudre'),
('Yaourt nature'),
('Nutella'),
('Muffin'),
('Gratin de courgettes au chèvre'),
('Courgette'),
('Gruyère râpé'),
('Crème épaisse'),
('Ail'),
('Chèvre'),
('Muscade'),
('Gratin de légumes'),
('Tiramisu au café'),
('Biscuits à la cuillère'),
('Mascarpone'),
('Café'),
('Cacao'),
('Marsala'),
('Tiramisu'),
('Mousse au chocolat de maman'),
('Chocolat'),
('Mousse'),
('Gâteau aux pommes croustillant de maman'),
('Huile'),
('Gâteau aux pommes'),
('Madeleines salées courgette chorizo'),
('Chorizo'),
('Madeleines salées'),
('Muffins à la pâte à tartiner et aux pépites de chocolat '),
('Vanille'),
('Pâte à tartiner'),
('Pâtes au saumon fumé à la vince'),
('Sauce tomate'),
('Spaghetti'),
('Saumon fumé'),
('Citron'),
('Ciboulette'),
('Autres pâtes'),
('Pancake Moelleux : recette facile'),
('Beurre doux'),
('Meringue : recette facile'),
('Blanc d''oeuf'),
('Meringues'),
('Les Timbales de Jeanne (saumon à la mousse de courgettes au micro-ondes)'),
('Aneth'),
('Menthe'),
('Béchamel rapide et facile'),
('Béchamel'),
('Crème pâtissière'),
('Jaune d''oeuf'),
('Crème pâtissière'),
('Filet mignon en croûte'),
('Pâte feuilletée'),
('Oignon jaune'),
('Filet mignon'),
('Jambon blanc '),
('Crumble simple'),
('Autres crumbles'),
('Moyen'),
('Pain d''épices'),
('Anis'),
('Quatre-épices'),
('Cannelle'),
('Miel'),
('Gingembre'),
('Tarte aux pommes à l''Alsacienne'),
('Pâte brisée'),
('Tarte aux pommes'),
('Pancakes faciles et rapides'),
('Sauté de veau au chorizo'),
('Oignon'),
('Sauté de veau'),
('Pulpe de tomate'),
('Olives vertes'),
('Basilic'),
('Bouquet garni'),
('Cake salé au jambon et aux olives'),
('Dés de jambon'),
('Cake salé apéritif'),
('Hachis Parmentier'),
('Purée'),
('Tomate'),
('Viande hachée'),
('Herbes de Provence'),
('Parmesan');

--INSERT INTO account_has_ingredient(account_id, ingredient_id) VALUES

INSERT INTO recipe_has_ingredient(recipe_id, ingredient_id) VALUES
(1, 1),
(1, 48),
(1, 4),
(1, 5),
(1, 6),
(1, 7),
(1, 8),
(1, 9),
(2, 1),
(2, 10),
(2, 4),
(2, 11),
(2, 9),
(2, 12),
(2, 13),
(3, 1),
(3, 4),
(3, 2),
(3, 5),
(3, 8),
(3, 11),
(3, 9),
(3, 12),
(4, 14),
(4, 15),
(4, 8),
(4, 16),
(4, 17),
(4, 18),
(4, 19),
(4, 20),
(4, 21),
(5, 1),
(5, 8),
(5, 22),
(5, 23),
(5, 7),
(6, 1),
(6, 11),
(6, 8),
(6, 24),
(6, 4),
(6, 5),
(6, 9),
(6, 12),
(6, 25),
(6, 26),
(7, 27),
(7, 28),
(7, 15),
(7, 8),
(7, 23),
(7, 29),
(7, 30),
(7, 9),
(7, 31),
(7, 32),
(8, 2),
(8, 33),
(8, 8),
(8, 34),
(8, 9),
(8, 35),
(8, 36),
(8, 37),
(9, 38),
(9, 5),
(9, 2),
(9, 6),
(9, 9),
(10, 5),
(10, 2),
(10, 4),
(10, 9),
(10, 1),
(10, 39),
(10, 8),
(10, 22),
(10, 12),
(10, 13),
(11, 1),
(11, 11),
(11, 28),
(11, 39),
(11, 27),
(11, 9),
(11, 40),
(12, 1),
(12, 2),
(12, 5),
(12, 8),
(12, 41),
(12, 38),
(12, 9),
(12, 12),
(12, 42),
(13, 5),
(13, 43),
(13, 15),
(13, 44),
(13, 45),
(13, 19),
(13, 17),
(13, 46),
(13, 18),
(13, 47),
(14, 1),
(14, 48),
(14, 22),
(14, 49),
(14, 8),
(14, 9),
(14, 12),
(15, 48),
(15, 50),
(16, 27),
(16, 23),
(16, 51),
(16, 8),
(16, 15),
(16, 45),
(16, 9),
(16, 19),
(16, 30),
(16, 52),
(17, 5),
(17, 1),
(17, 8),
(17, 15),
(17, 12),
(18, 1),
(18, 2),
(18, 41),
(18, 12),
(18, 53),
(19, 54),
(19, 28),
(19, 55),
(19, 56),
(19, 57),
(19, 53),
(20, 1),
(20, 5),
(20, 2),
(20, 13),
(21, 58),
(21, 1),
(21, 24),
(21, 11),
(21, 4),
(21, 59),
(21, 60),
(22, 63),
(22, 6),
(22, 24),
(22, 4),
(22, 13),
(22, 9),
(23, 2),
(23, 39),
(23, 1),
(23, 22),
(23, 9),
(23, 12),
(24, 64),
(24, 39),
(24, 65),
(24, 66),
(24, 40),
(24, 67),
(24, 68),
(24, 69),
(24, 30),
(25, 1),
(25, 28),
(25, 11),
(25, 39),
(25, 70),
(25, 67),
(25, 9),
(25, 12),
(26, 71),
(26, 64),
(26, 72),
(26, 1),
(26, 5),
(26, 28),
(26, 8),
(26, 15),
(26, 73),
(26, 30),
(26, 74),
(26, 53),
(26, 75);

INSERT INTO recipe_has_tag(recipe_id, tag_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(1, 7),
(1, 8),
(1, 9),
(1, 10),
(1, 11),
(1, 12),
(2, 13),
(2, 2),
(2, 14),
(2, 4),
(2, 15),
(2, 9),
(2, 16),
(2, 17),
(2, 18),
(2, 11),
(2, 12),
(2, 19),
(3, 20),
(3, 2),
(3, 4),
(3, 21),
(3, 5),
(3, 8),
(3, 15),
(3, 9),
(3, 16),
(3, 22),
(3, 11),
(3, 12),
(4, 23),
(4, 24),
(4, 25),
(4, 8),
(4, 26),
(4, 27),
(4, 28),
(4, 29),
(4, 30),
(4, 31),
(4, 11),
(4, 12),
(5, 32),
(5, 2),
(5, 8),
(5, 33),
(5, 34),
(5, 7),
(5, 35),
(5, 11),
(5, 12),
(5, 19),
(6, 36),
(6, 2),
(6, 15),
(6, 8),
(6, 37),
(6, 4),
(6, 5),
(6, 9),
(6, 16),
(6, 38),
(6, 39),
(6, 40),
(6, 11),
(6, 12),
(7, 41),
(7, 42),
(7, 43),
(7, 25),
(7, 8),
(7, 34),
(7, 44),
(7, 45),
(7, 9),
(7, 46),
(7, 47),
(7, 48),
(7, 11),
(7, 12),
(8, 49),
(8, 21),
(8, 50),
(8, 8),
(8, 51),
(8, 9),
(8, 52),
(8, 53),
(8, 54),
(8, 55),
(8, 11),
(8, 12),
(8, 19),
(9, 56),
(9, 57),
(9, 5),
(9, 21),
(9, 6),
(9, 9),
(9, 58),
(9, 11),
(9, 12),
(9, 19),
(10, 59),
(10, 5),
(10, 21),
(10, 4),
(10, 9),
(10, 2),
(10, 60),
(10, 8),
(10, 33),
(10, 16),
(10, 17),
(10, 61),
(10, 11),
(10, 12),
(11, 62),
(11, 2),
(11, 15),
(11, 43),
(11, 60),
(11, 42),
(11, 9),
(11, 63),
(11, 64),
(11, 11),
(11, 12),
(11, 19),
(12, 65),
(12, 2),
(12, 21),
(12, 5),
(12, 8),
(12, 66),
(12, 57),
(12, 9),
(12, 16),
(12, 67),
(12, 40),
(12, 11),
(12, 12),
(13, 68),
(13, 5),
(13, 69),
(13, 25),
(13, 70),
(13, 71),
(13, 29),
(13, 27),
(13, 72),
(13, 28),
(13, 73),
(13, 74),
(13, 11),
(13, 12),
(14, 75),
(14, 2),
(14, 3),
(14, 33),
(14, 76),
(14, 8),
(14, 9),
(14, 16),
(14, 22),
(14, 11),
(14, 12),
(14, 19),
(15, 77),
(15, 3),
(15, 78),
(15, 79),
(15, 11),
(15, 12),
(15, 19),
(16, 80),
(16, 42),
(16, 34),
(16, 81),
(16, 8),
(16, 25),
(16, 71),
(16, 9),
(16, 29),
(16, 45),
(16, 82),
(16, 11),
(16, 12),
(16, 19),
(17, 83),
(17, 5),
(17, 2),
(17, 8),
(17, 25),
(17, 16),
(17, 84),
(17, 11),
(17, 12),
(17, 19),
(18, 85),
(18, 2),
(18, 21),
(18, 66),
(18, 16),
(18, 86),
(18, 87),
(18, 11),
(18, 12),
(19, 88),
(19, 89),
(19, 43),
(19, 90),
(19, 91),
(19, 92),
(19, 86),
(19, 11),
(19, 12),
(20, 93),
(20, 2),
(20, 5),
(20, 21),
(20, 17),
(20, 94),
(20, 11),
(20, 95),
(21, 96),
(21, 2),
(21, 15),
(21, 97),
(21, 98),
(21, 99),
(21, 16),
(21, 11),
(21, 100),
(21, 37),
(21, 4),
(21, 101),
(21, 47),
(21, 9),
(21, 96),
(21, 95),
(22, 102),
(22, 103),
(22, 6),
(22, 37),
(22, 4),
(22, 17),
(22, 9),
(22, 104),
(22, 11),
(22, 12),
(23, 105),
(23, 21),
(23, 60),
(23, 2),
(23, 33),
(23, 9),
(23, 16),
(23, 22),
(23, 11),
(23, 12),
(23, 19),
(24, 106),
(24, 107),
(24, 60),
(24, 108),
(24, 109),
(24, 63),
(24, 110),
(24, 111),
(24, 112),
(24, 45),
(24, 11),
(24, 12),
(25, 113),
(25, 2),
(25, 43),
(25, 15),
(25, 60),
(25, 114),
(25, 110),
(25, 9),
(25, 16),
(25, 115),
(25, 11),
(25, 95),
(26, 116),
(26, 107),
(26, 2),
(26, 43),
(26, 25),
(26, 45),
(26, 86),
(26, 12),
(26, 117),
(26, 118),
(26, 5),
(26, 8),
(26, 119),
(26, 120),
(26, 121),
(26, 11);

COMMIT;
